cmd/k8s-operator: helm chart add missing keys
tailscale/tailscale pull request #10296
Opened 2023-11-16 23:41 UTC by GMartinez-Sisti

Closes https://github.com/tailscale/tailscale/issues/10182.

Add missing keys to helm chart default values.

2023-11-17 12:41 UTC, PaulSonOfLars commented
I believe this is missing the  `.Values.oauth` fields (in the secret template).

(apologies if this next bit is out of scope for this PR - just a passing thought)
Would it be worth using an boolean to enable/disable secrets? This would allow for demonstrating that the field exists, without it being set.

eg:

```
{{ if and .Values.oauth .Values.oauth.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: {{ .Release.Namespace }}
stringData:
  client_id: {{ .Values.oauth.clientId }}
  client_secret: {{ .Values.oauth.clientSecret }}
{{- end -}}
```

2023-11-17 17:03 UTC, GMartinez-Sisti commented
> I believe this is missing the `.Values.oauth` fields (in the secret template).
> 
> (apologies if this next bit is out of scope for this PR - just a passing thought. Happy to open a PR for it if requested) Would it be worth using a boolean to enable/disable secrets? This would allow for demonstrating that the field exists, without it being set.
> 
> eg:
> 
> ```
> {{ if and .Values.oauth .Values.oauth.create -}}
> apiVersion: v1
> kind: Secret
> metadata:
>   name: operator-oauth
>   namespace: {{ .Release.Namespace }}
> stringData:
>   client_id: {{ .Values.oauth.clientId }}
>   client_secret: {{ .Values.oauth.clientSecret }}
> {{- end -}}
> ```

Hi @PaulSonOfLars! Those values are commented on the first lines of the values chart:

https://github.com/tailscale/tailscale/blob/456c9c4d3aacfba8e883377b2f5e9f97c53d1c65/cmd/k8s-operator/deploy/chart/values.yaml#L4-L9

I didn't uncomment or the current logic would be broken:

https://github.com/tailscale/tailscale/blob/456c9c4d3aacfba8e883377b2f5e9f97c53d1c65/cmd/k8s-operator/deploy/chart/templates/oauth-secret.yaml#L4

I like your approach but that would be a breaking change. Waiting for the maintainers opinion.

2023-11-20 07:43 UTC, irbekrm requested changes
Thank you for the PR @GMartinez-Sisti !

Looks good to me except for the resource values- I left a comment there.

2023-11-20 07:59 UTC, irbekrm commented
>Hi @PaulSonOfLars! Those values are commented on the first lines of the values chart:

Looks like the oauth block in `values.yaml` is easy to miss as it's all commented out and blends in with the licence header above.
We could uncomment line 7 and make it `oauth: {}` that will work with the current syntax as [helm considers an empty map a nil value](https://helm.sh/docs/chart_template_guide/control_structures/#ifelse) - and should hopefully make it more noticeable.

2023-11-22 00:16 UTC, GMartinez-Sisti commented on cmd/k8s-operator/deploy/chart/values.yaml
> +  #   memory: 128Mi
I agree. Removed.

2023-11-22 11:01 UTC, irbekrm approved these changes
Thank you for the PR and for making the change!

2023-11-22 11:02 UTC, merged