api.md: document device invite apis
tailscale/tailscale pull request #12064
Opened 2024-05-08 21:26 UTC by soniaappasamy

Updates #18153

2024-05-08 21:26 UTC, soniaappasamy commented
Leaving in draft until the feature flag has been turned on

2024-05-09 13:14 UTC, deidraklieb commented
Removing myself from this review because @armstrongl is the Docs owner for APIs, per [go/which](https://docs.google.com/spreadsheets/d/1UPTRJM1YHO9S7kvrFnfoEkgEA1_aVZ90zXuzwyR6Jco/edit#gid=0).

2024-05-09 16:28 UTC, soniaappasamy commented on api.md
> +A device invite is an invitation that shares a device with a user external to the device's tailnet
```suggestion
A device invite is an invitation that shares a device with an external user (a user not in the device's tailnet).
```

2024-05-09 16:28 UTC, soniaappasamy commented on api.md
> +
```suggestion

Each invite request is an object with the following optional fields:

```

2024-05-09 16:30 UTC, soniaappasamy commented on api.md
> +All device invite IDs for a paricular device can be found by [listing all device invites for a device](#list-device-invites)
```suggestion
All device invite IDs for a particular device can be found by [listing device invites](#list-device-invites).
```

2024-05-09 17:13 UTC, catzkorn commented on api.md
> +```json
Same here

2024-05-09 17:13 UTC, catzkorn commented on api.md
> +```
Can we add the `http` identifier here? we have it on some of the others

2024-05-09 17:14 UTC, catzkorn commented on api.md
> +```json
Whoops, I messed up my comments. Can we use `jsonc` here? :D

2024-05-15 17:11 UTC, armstrongl requested changes

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +```
```suggestion
```http
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +```
```suggestion
```sh
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +```json
```suggestion
```jsonc
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +```
```suggestion
```http
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +or just the "{code}" component of the above URL.
```suggestion
The URL of the invite (in the form "https://login.tailscale.com/admin/invite/{code}") or the "{code}" component of the above URL.
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +Note that invite resends are rate limited to once per minute.
```suggestion
Resend the specified device invite by email. You can only use this if the specified invite was originally created with an email specified. Refer to [creating device invites for a device](#create-device-invites).

Note: Invite resends are rate limited to one per minute.
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +Note that invite resends are rate limited to once per minute.
```suggestion
Resend the specified device invite by email. You can only use this if the specified invite was originally created with an email specified. Refer to [creating device invites for a device](#create-device-invites).

Note: Invite resends are rate limited to one per minute.
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +All device invite IDs for a paricular device can be found by [listing all device invites for a device](#list-device-invites)
```suggestion
Each device invite has a unique ID that is used to identify the invite in API calls.
You can find all device invite IDs for a particular device by [listing all device invites for a device](#list-device-invites).
```

2024-05-15 17:11 UTC, armstrongl commented on api.md
> +- **`email`:** Optionally specifies the email to which to send the created invite. If not set, an invite URL is generated and returned, but not sent out.
```suggestion
- **`multiUse`:** (Optional) Specify whether the invite can be accepted more than once. When set to `true`, it results in an invite that can be accepted up to 1,000 times.
- **`allowExitNode`:** (Optional) Specify whether the invited user can use the device as an exit node when it advertises as one.
- **`email`:** (Optional) Specify the email to send the created invite. If not set, the endpoint generates and returns an invite URL (but doesn't send it out).
```

2024-05-15 17:31 UTC, soniaappasamy commented
@armstrongl updated!

2024-05-15 17:53 UTC, merged