api.md: document user invite apis
tailscale/tailscale pull request #12074
Opened 2024-05-09 16:45 UTC by soniaappasamy

Updates tailscale/corp#18153

2024-05-09 16:45 UTC, soniaappasamy commented
Leaving in draft until the feature flag has been turned on

2024-05-15 15:18 UTC, mpminardi commented on api.md
> +```json
Nit:
```suggestion
```jsonc
```

2024-05-15 15:26 UTC, mpminardi commented on api.md
> +  // id (strings) is the unique identifier for the invite.
Nit:
```suggestion
  // id (string) is the unique identifier for the invite.
```

2024-05-15 15:32 UTC, mpminardi approved these changes

2024-05-15 16:48 UTC, armstrongl requested changes

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +The tailnet user invite methods are provided for creating and listing invites for users to join a tailnet.
```suggestion
The tailnet user invite methods let you create and list [invites](https://tailscale.com/kb/1371/invite-users).
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +```
```suggestion
```sh
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +```
```suggestion
```http
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +List all open (not yet accepted) user invites for the tailnet.
```suggestion
List all user invites that haven't been accepted.
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +```
```suggestion
```http
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +```
```suggestion
```sh
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +All user invite IDs for a paricular tailnet can be found by [listing user invites](#list-user-invites).
```suggestion
You can find all user invite IDs for a particular tailnet by [listing user invites](#list-user-invites).
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +A user invite is an active invitation that allows a user to join a tailnet with a pre-assigned role.
```suggestion
A user invite is an active invitation that lets a user join a tailnet with a pre-assigned [user role](https://tailscale.com/kb/1138/user-roles).
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +- **`email`:** Optionally specifies the email to which to send the created invite. If not set, an invite URL is generated and returned, but not sent out.
```suggestion
Each invite request is an object with the following optional fields:

- **`role`:** (Optional) Specify a [user role](https://tailscale.com/kb/1138/user-roles) to assign the invited user. Defaults to the `"member"` role. Valid options are:
  - `"member"`: Assign the Member role.
  - `"admin"`: Assign the Admin role.
  - `"it-admin"`: Assign the IT admin role.
  - `"network-admin"`: Assign the Network admin role.
  - `"billing-admin"`: Assign the Billing admin role.
  - `"auditor"`: Assign the Auditor role.
- **`email`:** (Optional) Specify the email to send the created invite. If not set, the endpoint generates and returns an invite URL (but doesn't send it out).
```

2024-05-15 16:48 UTC, armstrongl commented on api.md
> +Note that invite resends are rate limited to once per minute.
```suggestion
Resend the specified user invite by email. You can only use this if the specified invite was originally created with an email specified. Refer to [creating user invites for a tailnet](#create-user-invites).

Note: Invite resends are rate limited to one per minute.
```

2024-05-15 16:58 UTC, soniaappasamy commented on api.md
> +All user invite IDs for a paricular tailnet can be found by [listing user invites](#list-user-invites).
oh muchhhh better! ty

2024-05-15 17:02 UTC, armstrongl approved these changes
🙌

2024-05-15 17:12 UTC, merged