Fixing Code Quality Issues
tailscale/tailscale pull request #1342
Opened 2021-02-15 10:19 UTC by HarshCasper

### Description
Hi 👋 

I ran the DeepSource static analyzer on the forked copy of this repo and found some interesting code quality [issues](https://deepsource.io/gh/HarshCasper/tailscale/). This PR fixes a few of them.

### Summary of changes

- Combine multiple `append`s into a single call
- Fix check for empty string
- Remove unnecessary use of slice
- Added `.deepsource.toml` file

2021-02-15 12:56 UTC, bradfitz commented
None of these look like actual quality issues. These are just arbitrary style changes. The new code loses the explicitness of the old.

2021-02-17 05:23 UTC, bradfitz commented
I'm okay with some of these changes if you're open to doing edits on this PR. Are you?

If so, I'll let you know which.

2021-02-17 07:05 UTC, HarshCasper commented
> I'm okay with some of these changes if you're open to doing edits on this PR. Are you?
> 
> If so, I'll let you know which.

Sure. I would be more than happy to work on this :)

2021-03-02 18:39 UTC, bradfitz requested changes

2021-03-02 18:39 UTC, bradfitz commented on .deepsource.toml
> +version = 1
Please remove this file. This isn't something we'll be running regularly.

2021-03-02 18:39 UTC, bradfitz commented on disco/disco.go
> +		copy(p, a[:])
Please revert. I prefer the explicitness.

2021-03-02 18:39 UTC, bradfitz commented on net/packet/udp6.go
> +	binary.BigEndian.PutUint16(buf[46:48], ip4Checksum(buf))
Please revert. I prefer the explicitness.

2021-03-02 18:39 UTC, bradfitz commented on tailcfg/tailcfg.go
> +	copy(dst, pub[:])
Please revert. I prefer the explicitness.

2021-03-08 22:57 UTC, closed without merging