Make the deployment if an IngressClass optional with a default to true
tailscale/tailscale pull request #14153
Opened 2024-11-19 14:04 UTC by Rumbles

Add a variable to the k8s operator values which defaults to true, and use that to decide whether to install the IngressClass.

Links to #14152

2024-11-19 16:01 UTC, irbekrm requested changes
Thank you for the PR @Rumbles , I've added a nit to restructure the values, apart from that it makes sense to me.

Could you also link the issue in your commit message to pass our CI issue checker? 
i.e `Fixes tailscale/tailscale#14152` - see other commits in this repo

2024-11-19 16:07 UTC, Rumbles commented on cmd/k8s-operator/deploy/chart/values.yaml
> +  createIngressClass: true
Hi @irbekrm thanks for the review, I have updated my PR

2024-11-19 16:17 UTC, irbekrm commented on cmd/k8s-operator/deploy/chart/values.yaml
> +  createIngressClass: true
Thanks @Rumbles the code change looks good, could you just please squash this into a single signed commit and add that `Fixes <issue>` or `Updates <issue>` line to the actual commit message?
i.e like https://github.com/tailscale/tailscale/commit/00517c8189569171560c073cd983164ff7735e69

Apart from that looks good to go in

2024-11-19 17:17 UTC, Rumbles commented on cmd/k8s-operator/deploy/chart/values.yaml
> +  createIngressClass: true
Hi, squashed and amended @irbekrm

2024-11-19 18:09 UTC, Rumbles commented on cmd/k8s-operator/deploy/chart/values.yaml
> +  createIngressClass: true
Sorry I misunderstood that part of the message, commit updated

2024-11-20 06:43 UTC, irbekrm approved these changes
Thank you @Rumbles !

2024-11-20 06:43 UTC, merged

2024-11-20 06:56 UTC, irbekrm commented
@Rumbles `1.77.119` Tailscale dev helm chart will have this change

2024-11-20 06:57 UTC, Rumbles commented
Thanks for the info @irbekrm and the review/merge, I'm looking forward to trying it out :)

2024-11-20 07:12 UTC, irbekrm commented
> I'm looking forward to trying it out :)

Any feedback if you run into further issues is welcome, we might want to add some docs for running on vcluster at some point