Xe/test install script libvirtd
tailscale/tailscale pull request #1934
Opened 2021-05-15 19:21 UTC by Xe

- [x] Amazon Linux
- [x] Arch Linux
- [x] Centos 7
- [x] Centos 8
- [ ] Debian Bullseye
- [ ] Debian Buster
- [ ] Debian Sid
- [ ] Debian Stretch
- [ ] Fedora (34)
- [ ] OpenSUSE Leap 15.1
- [ ] OpenSUSE Leap 15.2
- [ ] OpenSUSE Tumbleweed
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 19.10
- [ ] Ubuntu 20.04
- [ ] Ubuntu 20.10
- [ ] Ubuntu 21.04

Testing methodology: Use the [nocloud](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) data source for cloud-init and a fleet of cloud-init enabled images. TODO(Xe): `md5sum lufta:~/dl/iso/qcow2` and write a simple cloud-init script to auto-login your instance to Tailscale.

Images were imported like this:

```console
$ sudo zfs create -o mountpoint=none rpool/ts

$ qemu-img info amzn2-kvm-2.0.20210427.0-x86_64.xfs.gpt.qcow2
image: amzn2-kvm-2.0.20210427.0-x86_64.xfs.gpt.qcow2
file format: qcow2
virtual size: 25 GiB (26843545600 bytes)
disk size: 591 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false

$ sudo zfs create -V 25G rpool/ts/amazon-linux
$ sudo qemu-img convert -O raw amzn2-kvm-2.0.20210427.0-x86_64.xfs.gpt.qcow2 /dev/zvol/rpool/ts/amazon-linux
```

My cloud-init script looked like this:

```yaml
#cloud-config
#vim:syntax=yaml

cloud_config_modules:
 - runcmd

cloud_final_modules:
 - [users-groups, always]
 - [scripts-user, once-per-instance]

users:
  - name: xe
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys: 
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPg9gYKVglnO2HQodSJt4z4mNrUSUiyJQ7b+J798bwD9 cadey@shachi

write_files:
  - path: /etc/cloud/cloud.cfg.d/80_disable_network_after_firstboot.cfg
    content: |
      # Disable network configuration after first boot
      network:
        config: disabled

runcmd:
 - [ yum, update, gnupg2 ]
 - [ "sh", "-c", "curl https://raw.githubusercontent.com/tailscale/tailscale/Xe/test-install-script-libvirtd/scripts/installer.sh | sh" ]
 - [ systemctl, enable, --now, tailscaled.service ]
 - [ sh, "-c", "sleep 2" ]
 - [ tailscale, up, "--authkey=lolnotpastingthathere" ]
```

If something hecks up, look in the system journal and try to find an error, then fix it by running the install steps by hand such that no human interaction is required.

2021-05-16 11:48 UTC, Xe commented
To run tumbleweed in a VM, you need to use the Tumbleweed JeOS OpenStack Cloud image from here: https://download.opensuse.org/tumbleweed/appliances/

2021-05-26 16:40 UTC, bradfitz commented on scripts/installer.sh
> +      $SUDO rpm --import https://pkgs.tailscale.com/$RELEASE/$OS/$VERSION/repo.gpg
tabs

2021-05-26 16:41 UTC, bradfitz requested changes
Many lines are indented with spaces instead of tabs. Use tabs for consistency.

2021-05-26 16:42 UTC, bradfitz commented
Either squash this down to 1 commit, or at least squash away interim WIP fixes like "scripts/installer: forgot a sigil"

2021-05-26 16:58 UTC, bradfitz commented on scripts/installer.sh
> +RELEASE="${RELEASE:-stable}"
Maybe `RELEASE="${TAILSCALE_RELEASE:-stable}"` ?

2021-05-26 18:10 UTC, bradfitz commented
LGTM but maybe @danderson has thoughts.

2022-01-11 18:08 UTC, bradfitz commented
Closing for now; seems stale.

2022-01-11 18:08 UTC, closed without merging