tailcfg & controlclient: add caching for Node
tailscale/tailscale pull request #2651
Opened 2021-08-13 22:08 UTC by JulianKnodt

This adds a sync.Pool for tailcfg.Node so that they are not allocated on every iteration. It
seems this is the only place that Nodes are being cloned, so we can hopefully save most of the
cost of cloning them all the time.

Signed-off-by: julianknodt <julianknodt@gmail.com>

2021-08-13 22:13 UTC, bradfitz commented
Sorry, this isn't necessarily safe and also doesn't look effective. It's not safe because we don't know where those Nodes might've escaped to, and it's not effective because the Puts in a loop mean that most won't be retained. Only a few will.

If we're going to reuse this memory between map updates, we don't need or want a sync.Pool at all: we have all the previous nodes already. We can just use the old ones with the same NodeIDs. But we have to make sure those update writes won't race with other parties still hanging on to those nodes. We have to make sure that's safe+documented first.

2021-08-13 22:13 UTC, bradfitz requested changes
See prior comment.

2021-08-13 22:47 UTC, JulianKnodt commented
Hm ok, I'll look at reusing memory more safely then w/o the pool

2021-08-16 18:49 UTC, JulianKnodt commented
Hm I'm just going to drop this as I'm not so sure what to mark downstream as it shouldn't be updated due to races, and also it seems like it'd be a much larger change than I expected.

2021-08-16 18:49 UTC, closed without merging