derp: update code comment for DERP phrase
tailscale/tailscale pull request #3907
Opened 2022-02-11 18:01 UTC by WalterHub

2022-02-11 18:05 UTC, bradfitz commented
Why? This adds a fifth worth that doesn't fit the acronym?

2022-02-11 18:14 UTC, WalterHub commented
There's 2 different phrases for DERP on the site and in public code.

Which of "Detour Encrypted Routing Protocol" and "Designated Encrypted Relay for Packets" should be the standard?

2022-02-13 17:03 UTC, bradfitz commented
topic for eng meeting! :)

2022-02-13 17:03 UTC, bradfitz commented
or recursive: DERP Encrypted Routing Protocol

2022-02-24 19:28 UTC, bradfitz requested changes

2022-02-24 19:28 UTC, bradfitz commented on derp/derp.go
> +// Package derp implements DERP, the Designated Encrypted Relay
I think the meeting ended on keeping it as either "Detour Encrypted Routing Protocol" or maybe making Detour be "Detoured". I forget.

2022-09-15 23:41 UTC, WalterHub commented
This pr is obsolete after https://github.com/tailscale/tailscale/pull/5652.

2022-09-15 23:41 UTC, closed without merging