wgengine/router: allow disco packets through iptables on Linux
tailscale/tailscale pull request #5474
Opened 2022-08-28 21:33 UTC by bradfitz

Fixes #3824

2022-08-28 22:14 UTC, DentonGentry approved these changes
Do we want to do this literally the day before we build 1.30?
There really isn't time to test it.

2022-08-28 22:34 UTC, bradfitz commented
What tests should we do? I see it counting up upon getting disco packets. And I made it best effort in case their kernel doesn't have u32 support.

2022-08-28 22:45 UTC, DentonGentry commented
I'd want to try it on a system which can't handle unaligned accesses (we'd expect these accesses to be aligned, and maybe iptables handles unaligned accesses anyway, but I'd like to try it). I have an RPi somewhere I can dust off to build a tailscaled for.

2022-08-28 23:23 UTC, bradfitz commented
I can test on arm. But I just realized I didn't test IPv6 and I think the rule offsets are wrong on v6.

2022-08-28 23:59 UTC, DentonGentry approved these changes
Go ahead and submit when ready, if we find anything we'll handle it then.

2022-08-29 00:32 UTC, danderson commented
IIRC comments didn't work on the busybox implementation of iptables, or some other old iptables binary. We hit a bunch of compat issues because of that. I would remove the comment if you want best compat. Which is a shame because the rule sure looks sketchy without an explanation :)

But I'm also not clear on why this is needed. If we're sending bidirectionally, the linux firewall is just like any other stateful firewall, and it'll all work out after a few packets.

2022-08-29 00:34 UTC, danderson commented
nvm on the "why do we need this", I went and read the original bug. I guess that danderson guy knows what he's talking about.

2022-08-29 01:05 UTC, danderson requested changes
Thinking more, I think this is unsafe as written. This allows any program on the system to receive network traffic they don't expect. A user might reasonably expect that a server behind their host firewall won't receive external traffic, but we're saying that any process can, as long as the packet has the right preamble. I think this is too wide a hole to open, especially if people are running random poorly written services on the assumption that the firewall is protecting them from RCE.

Looking at iptables now to see what we might add to improve this...

2022-08-29 01:11 UTC, danderson commented
Okay, `iptables-extensions` is as usual poor-to-useless for this problem.

IMO, if we want to do this with iptables, we'd have to make the match be specific to our magicsock port numbers, and update the rule whenever magicsock rebinds. It's an irritating amount of plumbing, and it creates brief races where the allowed packets don't go to the right destination... But I can't think of an obvious way to exploit that, and the race won't harm NAT traversal since a future packet will still get through and get everything working again.

Or we do the AF_PACKET+BPF trick, which we can do from pure Go without needing an ebpf compiler or any such machinery.

2022-08-29 01:49 UTC, bradfitz commented
> IMO, if we want to do this with iptables, we'd have to make the match be specific to our magicsock port numbers, and update the rule whenever magicsock rebinds. It's an irritating amount of plumbing, and it creates brief races where the allowed packets don't go to the right destination... But I can't think of an obvious way to exploit that, and the race won't harm NAT traversal since a future packet will still get through and get everything working again.

Not a terrible amount of plumbing. And once that's done we don't even need the scary-looking u32 match. We can just say "all UDP" and that's much more readable for admins.

> Or we do the AF_PACKET+BPF trick, which we can do from pure Go without needing an ebpf compiler or any such machinery.

What's that trick? Amusingly, Googling that yields [The wrong way to filter sockets with BPF](https://natanyellin.com/posts/ebpf-filtering-done-right/). 😂

2022-08-29 03:13 UTC, andrew-d commented
Y'all are really good at nerd-sniping 😂  Here's a commit with an example of the "BPF trick"–using a BPF packet filter to look for disco packets and then reading them in Go. I confirmed that it dumps disco packets on a machine running Tailscale, though I haven't tested it in cases where a firewall blocks them.

https://github.com/tailscale/tailscale/commit/4e3158464fde135c7e1945fb833e26b180f0ff03

2022-08-29 04:15 UTC, bradfitz commented
> Y'all are really good at nerd-sniping 😂 Here's a commit with an example of the "BPF trick"–using a BPF packet filter to look for disco packets and then reading them in Go. I confirmed that it dumps disco packets on a machine running Tailscale, though I haven't tested it in cases where a firewall blocks them.
>
> https://github.com/tailscale/tailscale/commit/4e3158464fde135c7e1945fb833e26b180f0ff03

Ah, fun! So we can make this be a 4th packet source in magicsock (v4, v6, derp, this)?

2022-08-29 04:15 UTC, bradfitz commented
(left some comments on that commit, in lieu of a PR)

2022-08-29 16:54 UTC, bradfitz commented
Closing this in favor of @andrew-d's WIP changes.

2022-08-29 16:54 UTC, closed without merging