ipn/ipnlocal: restrict peerAPI endpoints for UnsignedPeerAPIOnly nodes
tailscale/tailscale pull request #6471
Opened 2022-11-23 21:33 UTC by twitchyliquid64

Probably not a great idea if such nodes can hit things like taildrop. An allowlist we can add to seems appropriate.

Am I holding this right / Is `h.peerNode` going to be populated in the way I'm assuming? Does this fit with your plans for the ipnauth package?

2022-11-23 21:47 UTC, bradfitz requested changes
No, peer caps are what peerapi allows. This bool isn't named IngressOnly.

2022-11-23 22:25 UTC, twitchyliquid64 commented
The outcome I want is that we minimize the attack surface for unsigned nodes as much as possible. Control can set the file-sharing capability and set `UnsignedPeerAPIOnly`, which would mean that taildrop is driveable by a compromised control even if the tailnet is locked. Similarly with `/env`.

2022-11-23 23:17 UTC, bradfitz commented
Blocking Taildrop & debug SGTM. Something like https://github.com/tailscale/tailscale/pull/6475 ?

2022-11-24 00:09 UTC, twitchyliquid64 commented
Lol exactly XD

2022-11-24 00:09 UTC, closed without merging